# Generated by Django 4.1 on 2022-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwsCred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("access_key", models.CharField(max_length=100)),
                ("secreat_key", models.CharField(max_length=100)),
                ("aws_s3", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("last_modified_date", models.DateTimeField()),
                ("last_run_date", models.DateTimeField()),
                ("is_complete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SftpCred",
            fields=[
                (
                    "user_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("host", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("port", models.IntegerField(null=True)),
            ],
        ),
    ]
